defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: fennec_development

test:
  <<: *defaults
  database: fennec_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true